spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.campus
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
